"""
run_pipeline.py — TBC-ML-Pipeline entry point

Automatically detects whether ABAQUS is available.
  - ABAQUS found     → full pipeline: generate cards → simulate → train → plot
  - ABAQUS not found → skip simulation stages, use pre-built dataset, train → plot

Expected repository layout after a run:
  results/
    dataset.json        ← pre-built dataset (committed to repo); also written here
                          when ABAQUS is available
    ml_results.json     ← train_model.py output
    ml_results.png      ← train_model.py output
    parity_plot.png     ← tbc_plots.py output
    surface_plots.png   ← tbc_plots.py output
    model_comparison.png← tbc_plots.py output
  results_ml/
    dataset.json        ← generated by abaqus_ml_pipeline.py (ABAQUS runs only)
  out_dir/
    *.inp               ← ABAQUS input cards generated by generate_cards.py
"""

import os
import sys
import subprocess
import shutil


# ──────────────────────────────────────────────
#  Directory paths  (all anchored to repo root)
# ──────────────────────────────────────────────
ROOT       = os.path.dirname(os.path.abspath(__file__))
SRC        = os.path.join(ROOT, "src")
DATA       = os.path.join(ROOT, "data")
RESULTS    = os.path.join(ROOT, "results")       # all final outputs
OUT_DIR    = os.path.join(ROOT, "out_dir")       # ABAQUS input cards
RESULTS_ML = os.path.join(ROOT, "results_ml")   # intermediate pipeline data

DATASET  = os.path.join(RESULTS_ML, "dataset.json")  # generated by ABAQUS run
PREBUILT = os.path.join(RESULTS,    "dataset.json")   # committed to repo


def banner(text: str) -> None:
    width = 60
    print()
    print("=" * width)
    print(f"  {text}")
    print("=" * width)


def check_abaqus() -> bool:
    """Return True if the 'abaqus' executable is on PATH."""
    return shutil.which("abaqus") is not None


def find_ml_python() -> str:
    """
    Return a Python executable suitable for ML stages (train_model, tbc_plots).

    The ABAQUS Python bundles its own Intel MKL which conflicts with scipy's
    LAPACK calls (DGELSD error).  If run_pipeline.py is launched from within
    the ABAQUS Python, we fall back to the system 'python' or 'python3'
    on PATH for the two ML stages.
    """
    if "SIMULIA" not in sys.executable and "abaqus" not in sys.executable.lower():
        return sys.executable   # already a standard Python — use it

    # Try common system Python names in order
    for name in ("python", "python3"):
        candidate = shutil.which(name)
        if candidate and "SIMULIA" not in candidate and "abaqus" not in candidate.lower():
            return candidate

    # Last resort: hope sys.executable works (user may have fixed MKL themselves)
    return sys.executable


def run(cmd: list, cwd: str = ROOT) -> None:
    """Run *cmd* in *cwd*, stream output live, and exit on failure."""
    print(f"\n> {' '.join(cmd)}\n")
    result = subprocess.run(cmd, cwd=cwd)
    if result.returncode != 0:
        print(f"\nERROR: command failed with exit code {result.returncode}")
        sys.exit(result.returncode)


def ensure_dirs() -> None:
    """Create all required output directories if they do not exist."""
    for d in (RESULTS, RESULTS_ML, OUT_DIR):
        os.makedirs(d, exist_ok=True)


def ensure_dataset() -> None:
    """
    Guarantee results_ml/dataset.json exists before ML training.
    Copies the pre-built results/dataset.json when ABAQUS was not run.
    """
    if os.path.exists(DATASET):
        print(f"  Dataset present: {DATASET}")
        return
    if os.path.exists(PREBUILT):
        shutil.copy(PREBUILT, DATASET)
        print(f"  Pre-built dataset copied to: {DATASET}")
    else:
        print("\nERROR: No dataset found.")
        print("  Expected one of:")
        print(f"    {DATASET}")
        print(f"    {PREBUILT}")
        print("\n  Options:")
        print("    1. Install ABAQUS and run the full pipeline.")
        print("    2. Download dataset.json from the repository and place it in:")
        print(f"       {RESULTS}")
        sys.exit(1)



# ──────────────────────────────────────────────
#  Main
# ──────────────────────────────────────────────
def main() -> None:
    banner("TBC-ML-Pipeline")

    ensure_dirs()
    abaqus_available = check_abaqus()

    if abaqus_available:
        print("  ABAQUS detected — running full pipeline.\n")
        print("  Stages:")
        print("    [1] Generate ABAQUS input cards")
        print("    [2] Run simulations and extract results")
        print("    [3] Train ML model")
        print("    [4] Generate plots")
    else:
        print("  ABAQUS not found — skipping simulation stages.")
        print("  Pre-built dataset will be used for ML training.\n")
        print("  Stages:")
        print("    [1] Generate ABAQUS input cards  →  SKIPPED")
        print("    [2] Run simulations               →  SKIPPED")
        print("    [3] Train ML model                →  will run")
        print("    [4] Generate plots                →  will run")

    # ── Stage 1: Generate input cards ──────────────────────
    banner("Stage 1 — Generate ABAQUS Input Cards")

    if abaqus_available:
        run([
            sys.executable,
            os.path.join(SRC, "generate_cards.py"),
            os.path.join(DATA, "materials.json"),
            OUT_DIR,
        ])
    else:
        print("  Skipped (ABAQUS not available).")

    # ── Stage 2: Run ABAQUS simulations ────────────────────
    banner("Stage 2 — Simulate and Extract Results")

    if abaqus_available:
        run([sys.executable, os.path.join(SRC, "abaqus_ml_pipeline.py")])
    else:
        print("  Skipped (ABAQUS not available).")
        print("  Loading pre-built dataset instead...")
        ensure_dataset()

    # ── Stage 3: Train ML model ─────────────────────────────
    banner("Stage 3 — Train ML Model")

    ml_python = find_ml_python()
    if ml_python != sys.executable:
        print(f"  Using system Python for ML stages: {ml_python}")

    run([ml_python, os.path.join(SRC, "train_model.py")])

    # ── Stage 4: Generate visualisation plots ───────────────
    banner("Stage 4 — Generate Plots")

    run([
        ml_python,
        os.path.join(SRC, "tbc_plots.py"),
        "--out-dir", RESULTS,
    ])

    # ── Done ────────────────────────────────────────────────
    banner("Pipeline Complete")
    print("  All outputs written to:  results/")
    print()
    print("  Results:")
    for fname in (
        "dataset.json",
        "ml_results.json",
        "ml_results.png",
        "parity_plot.png",
        "surface_plots.png",
        "model_comparison.png",
    ):
        path = os.path.join(RESULTS, fname)
        status = "OK" if os.path.exists(path) else "MISSING"
        print(f"    [{status:^7}]  results/{fname}")
    print()


if __name__ == "__main__":
    main()